# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noisesearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document_single',
            old_name='document',
            new_name='single',
        ),
        migrations.RemoveField(
            model_name='document_multiple',
            name='document',
        ),
        migrations.AddField(
            model_name='document_multiple',
            name='multiple',
            field=models.FileField(default=1, upload_to='documents/multiple/'),
            preserve_default=False,
        ),
    ]
